### Slicing Strings
A section of an array is called a `slice`. We can take slices of character strings as well:

Python:
```python
element = 'oxygen'
print('first three characters:', element[0:3])
print('last three characters:', element[3:6])
```
Output:
```
first three characters: oxy
last three characters: gen
```

What is the value of `element[:4]`? What about `element[4:]`? Or `element[:]`?

In [2]:
element = 'oxygen'
print(element[:4])
print(element[4:])
print(element[:])

oxyg
en
oxygen


What is `element[-1]`? What is `element[-2]`?

In [4]:
print(element[-1])
print(element[-2])

n
e


Given those answers, explain what `element[1:-1]` does.

In [6]:
element[1:-1]
element[1:5]

'xyge'

---

### Thin Slices
The expression `element[3:3]` produces an empty string, i.e., a string that contains no characters.  
If `data` holds our array of patient data, what does `data[3:3, 4:4]` produce? What about `data[3:3, :]`?

In [16]:
import numpy
data = numpy.loadtxt(fname='../inflammation-01.csv', delimiter=',')
element[3:3]
print(data[3:3, 4:4])

[]


---

### Drawing Straight Lines
In the center and right subplots above, we expect all lines to look like step functions because non-integer value are not realistic for the minimum and maximum values. However, you can see that the lines are not always vertical or horizontal, and in particular the step function in the subplot on the right looks slanted. Why is this?

---

### Make Your Own Plot

Create a plot showing the standard deviation (`numpy.std`) of the inflammation data for each day across all patients.

---

### Moving Plots Around
Modify the program to display the three plots on top of one another instead of side by side.

---

### Stacking Arrays
Arrays can be concatenated and stacked on top of one another, using NumPy’s `vstack` and `hstack` functions for vertical and horizontal stacking, respectively.

Input:
```python
import numpy

A = numpy.array([[1,2,3], [4,5,6], [7, 8, 9]])
print('A = ')
print(A)

B = numpy.hstack([A, A])
print('B = ')
print(B)

C = numpy.vstack([A, A])
print('C = ')
print(C)
```

Output:
```
A =
[[1 2 3]
 [4 5 6]
 [7 8 9]]
B =
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
C =
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]
```

Write some additional code that slices the first and last columns of `A`, and stacks them into a 3x2 array.  
Make sure to print the results to verify your solution.

---

### Change In Inflammation
This patient data is longitudinal in the sense that each row represents a series of observations relating to one individual. This means that the change in inflammation over time is a meaningful concept.

The `numpy.diff()` function takes a NumPy array and returns the differences between two successive values along a specified axis. For example, a NumPy array that looks like this:

Python:
```python
npdiff = numpy.array([ 0,  2,  5,  9, 14])
```

Calling `numpy.diff(npdiff)` would do the following calculations and put the answers in another array.

Output:
```
[ 2 - 0, 5 - 2, 9 - 5, 14 - 9 ]
```

Python:
```python
numpy.diff(npdiff)
```

Output:
```
array([2, 3, 4, 5])
```
Which axis would it make sense to use this function along?

If the shape of an individual data file is `(60, 40)` (60 rows and 40 columns), what would the shape of the array be after you run the `diff()` function and why?

How would you find the largest change in inflammation for each patient? Does it matter if the change in inflammation is an increase or a decrease?

---